version: "3.11.7"

services:
  rag-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rag-fastapi-app
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
